### ISSUE TITLE
Bugs on using new relic with next js

### ISSUE THREAD

**Issue by karlo-humanmanaged** [newrelic/newrelic-node-nextjs#136]
Here are some bugs I encountered when trying to integrate New Relic to our NextJS application:

We're using Vercel and we currently have the issue in https://github.com/newrelic/newrelic-node-nextjs/issues/135. I think newrelic needs to create a nextjs middleware (similar to "next-auth/middleware" "withAuth") that does similar things as the one you're loading with '-r @newrelic/next''.

Also, in my local, I modified my "dev" script like
```
NODE_OPTIONS='-r @newrelic/next' next dev
```
and added `newrelic.js` in my application root.
The problem here is that when I reference `process.env.NEW_RELIC_LICENSE_KEY` within `newrelic.js`, it is coming out as `undefined` (even if I have NEW_RELIC_LICENSE_KEY in my `env.local`) . If I hardcode the license_key value, everything works in local.

Lastly, if I use an `INGEST - BROWSER` type license key, it is coming out as an Invalid License Key, but if I use `INGEST - LICENSE` type, then it works. Our new relic instance is in EU if that matters.

**Comment by bizob2828** [comment]
@karlo-humanmanaged I want to make sure I answer all your concerns to make sure there isn't any uknown issues here.

> We're using Vercel and we currently have the issue in https://github.com/newrelic/newrelic-node-nextjs/issues/135. I think newrelic needs to create a nextjs middleware (similar to "next-auth/middleware" "withAuth") that does similar things as the one you're loading with '-r @newrelic/next''.

We are aware that this package does not work in Vercel at the moment.  We have an item on our roadmap to have a solution to this.

> it is coming out as undefined (even if I have NEW_RELIC_LICENSE_KEY in my env.local) 

We have found that this is a next.js construct to parse the env.local but since our instrumentation runs in a `-r` the next CLI cannot parse the env.local.  Your solution would have to be to do something like this:

```
npm i dotenv
NODE_OPTIONS='-r dotenv/config -r @newrelic/next' next dev
```

> Lastly, if I use an INGEST - BROWSER type license key, it is coming out as an Invalid License Key, but if I use INGEST - LICENSE type, then it works. Our new relic instance is in EU if that matters.

Yes that is correct.  This package is maintained by the Node.js agent team and you need the `INGEST - LICENSE` type not the `INGEST - BROWSER`.
