### ISSUE TITLE
TypeError: Illegal invocation (t.sendObjectBeacon(beacon.min.js/<UNIQUE_IDENTIFIER>)

### ISSUE THREAD

**Issue by Pranav2111** [newrelic/newrelic-node-nextjs#199]
- I am using browser agent for my Next JS application. I have integrated it using APM. I am getting following error very frequently in my application "**t.sendObjectBeacon(beacon.min.js/<UNIQUE_IDENTIFIER>**" .
- I am attaching the screenshot of my sentry issue and error frequency for reference.
- I am using Node JS agent for APM
- I have referred official doc to setup browser agent for my Next JS application. Here is the link for reference - https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data

![Screenshot from 2024-05-30 09-21-15](https://github.com/newrelic/newrelic-node-nextjs/assets/56624008/ac597311-93d8-4302-8fb3-935993101d3c)

![image (2)](https://github.com/newrelic/newrelic-node-nextjs/assets/56624008/37045eb1-01bb-4dd3-a1fc-c961303d860f)

![Screenshot from 2024-05-30 09-20-39](https://github.com/newrelic/newrelic-node-nextjs/assets/56624008/bda660c7-e741-4b72-b222-486f13f4a4f7)

**Comment by jsumners-nr** [comment]
For help on how to instrument Next.js with our agents, please refer to one of our [example apps](https://github.com/newrelic/newrelic-node-nextjs/blob/ea20b76a13c84f4f3c48e9544e18e568b8e41c33/README.md#example-projects). If you are still having issues with the browser agent, please direct questions about it to the [browser agent team](https://github.com/newrelic/newrelic-browser-agent).

**Comment by bizob2828** [comment]
@Pranav2111 I've reached out to the browser agent team. They're going to take a look

**Comment by jsumners-nr** [comment]
I think we can close this as out of scope for this repo. Please follow up with the browser agent team if you need more assistance on this particular issue.

**Comment by patrickhousley** [comment]
Hi @Pranav2111 . We use `sendBeacon` when the page backgrounded or navigated away from to perform a final harvest of data. We have already surrounded the call in a `try..catch` some time ago to catch and ignore these illegal invocation errors. Unfortunately, it's an issue with the browser's implementation of `sendBeacon`. You can scour the internet to see that this issue has plagued the likes of Google Tag Manager, and other RUM implementation that rely on `sendBeacon`. Outside of using a `try..catch` to ignore the error as [we have already done](https://github.com/newrelic/newrelic-browser-agent/blob/main/src/common/util/submit-data.js#L64), there isn't much else we can do given the browser's implementation. I do find it strange that sentry is picking up the error since we are technically catching and handling it in our own code. You may want to talk to sentry about how they are doing this and if the error can be ignored on their end.

For now, I am going to close this issue. Feel free to open a new one on our [repo](https://github.com/newrelic/newrelic-browser-agent/issues) if you still have questions or concerns.
